### PR TITLE
feat: fetch forest client by acronym

### PR DESCRIPTION
**Pull request by annibalsilva**
# Description

Modify the existing endpoint to fetch forest clients (`/api/forest-clients/{number}`) so that it's possible to fetch a client by acronym as well.

Fixes [FSADT2-658](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT2-658)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

- [x] Unit tests
- [x] Manual tests

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have already been accepted and merged

## Further comments

---
Thanks for the PR!

Any successful deployments (not always required) will be available below.
[Backend](https://nr-spar-94-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-94-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-94-oracle-api.apps.silver.devops.gov.bc.ca/)

Once merged, code will be promoted and handed off to following workflow run.
[Main Merge Workflow](https://github.com/bcgov/nr-spar/actions/workflows/merge-main.yml)

### CODE REVIEW

**Comment by DerekRoberts** [comment]
@annibalsilva Good job catching the fails and making this PR as draft!  We're working on some documents to make these processes easier to share.  :)

**Comment by annibalsilva** [comment]
@DerekRoberts As a feedback, I find it odd that deployment is done for draft PRs but CI and code quality aren't. I expected it to be the other way around: the CI pipeline looks "cheaper", so it could be ran more frequently (and we get information about things like code coverage and bugs we may have introduced in the code) and deployment implies a bigger commitment to me.

**Review by DerekRoberts — APPROVED** [review]
Looks good!  :)

**Review by RMCampos — APPROVED** [review]
Great job!! 🥇 🎈

**Comment by RMCampos** [comment]
Notes: @craigyu and @annibalsilva 

- If we try a client number with less than 8 numbers, it will respond with 404. It's not an issue, just want to highlight.
- In case the database has more than one record for the identifier, we'll return the first one (I'm glad that Annibal added a log for these cases)

**Pull request merged**
