### PR TITLE
Fix/199 orchard step pollen information section

### LINKED ISSUE #199: Orchard step pollen information section not working properly
**Describe the Bug**
Orchard step pollen information section not working properly.

**Expected Behaviour**
"Contaminant pollen breeding percentage" and "Contaminant pollen methodology" fields should only show when the "Was pollen contamination present?" field is set to false. Also, the "Contaminant pollen methodology" field should be true and read-only.

**Actual Behaviour**
All fields are appearing no matter the value set on "Was pollen contamination present?" and "Contaminant pollen methodology" field is not read-only.

** Steps To Reproduce**
Steps to reproduce the behaviour:
1. Go to Orchard Step when registering a seedlot
2. The fields will appear

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 113.0.5672.127

### PR DESCRIPTION
**Pull request by mgaseta**
# Description

Fixed Pollen Information section behavior and updated percentage field label. Also updated the static texts on the Orchard step component.

Fixes #199 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Manually tested and ran unit tests.

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have already been accepted and merged

## Further comments

---
Thanks for the PR!

Any successful deployments (not always required) will be available below.
[Backend](https://nr-spar-262-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-262-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-262-oracle-api.apps.silver.devops.gov.bc.ca/)

Once merged, code will be promoted and handed off to following workflow run.
[Main Merge Workflow](https://github.com/bcgov/nr-spar/actions/workflows/merge-main.yml)

### CODE REVIEW

**Review by craigyu — APPROVED** [review]
Nice 👑

**Comment by craigyu** [comment]
image

I does not show up for me :(

**Comment by mgaseta** [comment]
> image
> 
> I does not show up for me :(

It is showing here for me, any console errors?

**Comment by craigyu** [comment]
@mgaseta no errors, let's look at it together on tmr's sync meeting

**Review by craigyu — APPROVED** [review]
@mgaseta Sorry I was looking at the wrong checkbox 🤪, It's working as intended

**Pull request merged**
