### PR TITLE
fix: block navigation while in edit mode

### LINKED ISSUE #1635: Patch review navigate away confirm modal
Block users from navigating away from the seedlot review screen while in edit mode.

### PR DESCRIPTION
**Pull request by craigyu**
# Description
Closes #1635

#### New
- added useBlocker logic to seedlot review screen

#### Changed
- None

#### Removed
- None

### How was this tested?
- [ ] 🧠 Not needed
- [x] 👀 Eyeball
- [ ] 🤖 Added tests

###  What gif/image best describes this PR or how it makes you feel?

---

Thanks for the PR!

Deployments, as required, will be available below:
- [Frontend](https://nr-spar-36-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1636-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1636-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

Please create PRs in draft mode.  Mark as ready to enable:
- [Analysis Workflow](https://github.com/bcgov/nr-spar/actions/workflows/analysis.yml)

After merge, new images are deployed in:
- [Merge Workflow](https://github.com/bcgov/nr-spar/actions/workflows/merge.yml)

### CODE REVIEW

**Review by mgaseta — COMMENTED** [review]
Looking good, just one question: after clicking on the save or discard option in the popup, shouldn't the user be redirected to where he wanted to go?

**Comment by RMCampos** [comment]
> Looking good, just one question: after clicking on the save or discard option in the popup, shouldn't the user be redirected to where he wanted to go?

That's a good question. But I'd say it's out of scope. User can click again, imo.

**Review by RMCampos — APPROVED** [review]
LGTM

**Comment by mgaseta** [comment]
> > Looking good, just one question: after clicking on the save or discard option in the popup, shouldn't the user be redirected to where he wanted to go?
> 
> That's a good question. But I'd say it's out of scope. User can click again, imo.

That makes sense, approving it then!

**Review by mgaseta — APPROVED** [review]

**Pull request merged**
