### PR TITLE
feat: 1594 adjustments for orchard screen

### LINKED ISSUE #1594: Adjustments for step 4 - Orchard screen
**Describe the task**
During refinement some FE adjustments were identified for the step 4 - Orchard screen. They are:

1. Get rid of the plus/minus on the pollen breeding value field
2. Make drop down fields the same width
 
**Acceptance Criteria**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] QA from UX team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Additional context**

Image

### PR DESCRIPTION
**Pull request by ngunner15**
# Description
Closes #1594 

#### New
- Make drop-down fields the same width

#### Changed
- orchard cypress test(title and subtitle test)

#### Removed
- plus/minus on the pollen breeding value field

### How was this tested?
- [x] 🧠 Not needed
- [ ] 👀 Eyeball
- [ ] 🤖 Added tests

###  What gif/image best describes this PR or how it makes you feel?

---

Thanks for the PR!

Deployments, as required, will be available below:
- [Frontend](https://nr-spar-49-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1599-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1599-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

Please create PRs in draft mode.  Mark as ready to enable:
- [Analysis Workflow](https://github.com/bcgov/nr-spar/actions/workflows/analysis.yml)

After merge, new images are deployed in:
- [Merge Workflow](https://github.com/bcgov/nr-spar/actions/workflows/merge.yml)

### CODE REVIEW

**Review by Ding-x — APPROVED** [review]
lgtm

**Review by RMCampos — APPROVED** [review]
LGTM!

Good job Matheus and Nisarg!

**Review by RMCampos — CHANGES_REQUESTED** [review]
Still showing a blank orchard for me :(

**Comment by RMCampos** [comment]
> Still showing a blank orchard for me :(

Testing on Incognito browsing mode it worked. Approved

**Review by RMCampos — APPROVED** [review]
LGTM

**Pull request merged**
