### PR TITLE
Fix: readme, guides and docker compose files

### PR DESCRIPTION
**Pull request by RMCampos**
# Description

- Updates README files
- Updates CONTRIBUTING files
- Creates docker compose files for each service

Fixes [Jira Task 666](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT2-666) and #37 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

These changes were tested locally with Docker.

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have already been accepted and merged

## Further comments

---
Thanks for the PR!

Any successful deployments (not always required) will be available below.
[Backend](https://nr-spar-91-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-91-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-91-oracle-api.apps.silver.devops.gov.bc.ca/)

Once merged, code will be promoted and handed off to following workflow run.
[Main Merge Workflow](https://github.com/bcgov/nr-spar/actions/workflows/merge-main.yml)

### CODE REVIEW

**Comment by DerekRoberts** [comment]
> > Great progress! Please use only one docker-compose.yml in the repo root. The rest should be deleted.
> 
> Maybe we could have two. One with all four services, and another one with backend only (database plus two api). What do you think? @DerekRoberts

That means maintaining two compose files.  Please stick with one stack and let everyone get exposed to the same workflow.  If resources are an issue we can revisit.

**Comment by craigyu** [comment]
> > Great progress! Please use only one docker-compose.yml in the repo root. The rest should be deleted.
> 
> Maybe we could have two. One with all four services, and another one with backend only (database plus two api). What do you think? @DerekRoberts

I think we can specify which service to run like this https://stackoverflow.com/a/52021291
Will that be the solution?

We are planning to have DB running in docker as well, but that should be in another PR.

**Comment by RMCampos** [comment]
> docker as well, but that should be in another

I'm thinking for frontend development. We'll need all backend services running. But the frontend will run locally, not in docker. If we can specify which one we want, that works I think.

**Comment by DerekRoberts** [comment]
> 

We have control over what's started started by Docker Compose, but I want people seeing the whole stack.

E.g.  `docker-compose up -d <COMPONENT>`

**Review by craigyu — APPROVED** [review]

**Pull request merged**
