### PR TITLE
Feat/798 fill in seedlot form with seedlot table data for submitted seedlots

### LINKED ISSUE #907: integrate display submitted seedlot form data on test env
This issue is to review, fix then integrate the changes implemented from #798. 

Issue #798 introduced a lot of changes on the code base and requires extensive review and testing to make sure it's ready to be integrated. 

In hindsight the issue should've been split up into multiple stages. 

- [ ] Ownership title should display client name

### PR DESCRIPTION
**Pull request by mgaseta**
# Description
Closes #907 

Sorry about this giant PR and submitting most of the work in a giant commit, I know is against our team's development policy... But please pay a lot of attention when testing, I maybe became biased since I've been working on it for quite a while. Also, there is still a bug when displaying the name of each owner on step 2, but I think we can open a separate issue to deal with that (this PR is already waaaay to big). 

#### New
- New api integration to get all data from a seedlot

#### Changed
- Changed each init step function to initialize the step with all necessary data
- Changed the service on the backend to return each step separately
- Added new API calls to fetch the correct data to fill the form
- Hide some buttons when form is on read-only format

#### Removed
- Some unnecessary props

### How was this tested?
- [ ] 🧠 Not needed
- [x] 👀 Eyeball
- [ ] 🤖 Added tests

###  What gif/image best describes this PR or how it makes you feel?

---
Thanks for the PR!

Any successful deployments (not always required) will be available below.
[Frontend](https://nr-spar-13-frontend.apps.silver.devops.gov.bc.ca/)
[Backend](https://nr-spar-13-backend.apps.silver.devops.gov.bc.ca/actuator/health)
[Oracle-API](https://nr-spar-13-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

Once merged, code will be promoted and handed off to following workflow run.
[Main Merge Workflow](https://github.com/bcgov/nr-spar/actions/workflows/merge-main.yml)

### CODE REVIEW

**Review by craigyu — CHANGES_REQUESTED** [review]
Great work! Everything works 

There's a pain in the 🍑 task that you forgot, need to add the owner name in the accordion title:

image

**Comment by craigyu** [comment]
+1 for the gif, dangerously relatable

**Review by craigyu — APPROVED** [review]
oops, I didn't read your description careful enough, ok let's tackle the ownership title implementation in a separate issue. I'm intended to merge this in soon as I need your a-class-full-form front-end integration

**Review by RMCampos — APPROVED** [review]
Great job! 🥇

**Pull request merged**
