### PR TITLE
feat: 1201 adding submit daclaration info

### LINKED ISSUE #1201: Update endpoint for seedlot submission user ID and timestamp
**Describe the task**
The endpoint needs to be updated for the seedlot submission user ID and timestamp in the seedlot table. This endpoint will later be used for #856 

**Acceptance Criteria**
- [ ] endpoint updated
- [ ] tested and reviewed
- [ ] merged

### PR DESCRIPTION
**Pull request by mgaseta**
# Description
Closes #1201

#### New
- Added new function to set data on seedlot

#### Changed
- Nothing :)

#### Removed
- Nothing :)

### How was this tested?
- [x] 🧠 Not needed
- [ ] 👀 Eyeball
- [ ] 🤖 Added tests

###  What gif/image best describes this PR or how it makes you feel?

---

Thanks for the PR!

Deployments, as required, will be available below:
- [Frontend](https://nr-spar-14-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1214-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Oracle-API](https://nr-spar-1214-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

Please create PRs in draft mode.  Mark as ready to enable:
- [Analysis Workflow](https://github.com/bcgov/nr-spar/actions/workflows/analysis.yml)

After merge, new images are deployed in:
- [Merge Workflow](https://github.com/bcgov/nr-spar/actions/workflows/merge.yml)

---

Thanks for the PR!

Deployments, as required, will be available below:
- [Frontend](https://nr-spar-14-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1214-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1214-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

Please create PRs in draft mode.  Mark as ready to enable:
- [Analysis Workflow](https://github.com/bcgov/nr-spar/actions/workflows/analysis.yml)

After merge, new images are deployed in:
- [Merge Workflow](https://github.com/bcgov/nr-spar/actions/workflows/merge.yml)

### CODE REVIEW

**Review by craigyu — APPROVED** [review]
LGTM!

**Review by craigyu — COMMENTED** [review]
Actually can we add a couple lines of related tests in the seedlot reg form test?

**Review by RMCampos — CHANGES_REQUESTED** [review]
Good job! I'm with Craig, let's load some unit tests, then we're good to go. 🚀

**Review by RMCampos — APPROVED** [review]
Good job! 🥇

**Pull request merged**
