### PR TITLE
feat: replace webpack with vite

### LINKED ISSUE #54: Replace Webpack with Vite
**Describe the task**
A clear and concise description of what the task is.

Replace `react-scripts and webpack` with `vite`. (We already did this in the past, on the sample webapp, that now is merged into QuickStart template: https://github.com/bcgov/quickstart-openshift/blob/main/frontend-react/vite.config.ts)

**Acceptance Criteria**
- [x] Build and run locally smoothly
- [x] Build and fun smoothly on Docker
- [x] Tests passing locally
- [x] Tests passing on CI

**Additional context**
- With this task we also can remove that `env.js` file in `public.html` and use something else. Maybe update to use Caddy. But I'm not sure if could do all of that in the same issue.

### PR DESCRIPTION
**Pull request by RMCampos**
# Description

Remove `react-scripts` and `webpack` and add `vite` and `vitest`

Fixes #54 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

This was tested locally, with unit tests and with docker.

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have already been accepted and merged

## Further comments

---
Thanks for the PR!

Any successful deployments (not always required) will be available below.
[Backend](https://nr-spar-409-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-409-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-409-oracle-api.apps.silver.devops.gov.bc.ca/)

Once merged, code will be promoted and handed off to following workflow run.
[Main Merge Workflow](https://github.com/bcgov/nr-spar/actions/workflows/merge-main.yml)

### CODE REVIEW

**Review by DerekRoberts — APPROVED** [review]
That was a lot of change in a short time!  Kick ass.  :D

**Review by DerekRoberts — CHANGES_REQUESTED** [review]
No luck with the frontend.  :(
```
Uncaught TypeError: Cannot read properties of undefined (reading 'authorize')
    at Keycloak.a.createLoginUrl (index-040c81a1.js:153:16810)
    at Object.login (index-040c81a1.js:153:31705)
    at Keycloak.a.login (index-040c81a1.js:153:15759)
    at j (index-040c81a1.js:153:1932262)
    at onClick (index-040c81a1.js:153:1933090)
    at Object.Nb (index-040c81a1.js:37:9896)
    at Tb (index-040c81a1.js:37:10056)
    at Ub (index-040c81a1.js:37:10116)
    at nf (index-040c81a1.js:37:31598)
    at se (index-040c81a1.js:37:32042)
```

**Comment by RMCampos** [comment]
> No luck with the frontend. :'(
> 
> From web console:
> 
> ```
> Uncaught TypeError: Cannot read properties of undefined (reading 'authorize')
>     at Keycloak.a.createLoginUrl (index-040c81a1.js:153:16810)
>     at Object.login (index-040c81a1.js:153:31705)
>     at Keycloak.a.login (index-040c81a1.js:153:15759)
>     at j (index-040c81a1.js:153:1932262)
>     at onClick (index-040c81a1.js:153:1933090)
>     at Object.Nb (index-040c81a1.js:37:9896)
>     at Tb (index-040c81a1.js:37:10056)
>     at Ub (index-040c81a1.js:37:10116)
>     at nf (index-040c81a1.js:37:31598)
>     at se (index-040c81a1.js:37:32042)
> ```

Fixed!! Here: https://github.com/bcgov/nr-spar/pull/409/commits/8aace2da651b2d30fa62b5bf4f9beaaca956d56b

**Review by DerekRoberts — APPROVED** [review]
Good now!  Merge away.  :)

**Comment by craigyu** [comment]
Lightning fast! 🏎️

image

**Review by craigyu — APPROVED** [review]
Great work, especially on doing all that prison work refactoring tests

**Pull request merged**
