### PR TITLE
Feat: Genetic Worth Calculations API

### LINKED ISSUE #240: Genetic Worth calculation API development
Implement the calculation of the genetic worth of a seedlot

Implement the calculation of the genetic worth of a seedlot according to the formula of the attached workbook.

Genetic worth

Genetic worth, as defined in [Chief Forester's Standards for Seed Use](https://www2.gov.bc.ca/assets/gov/farming-natural-resources-and-industry/forestry/tree-seed/legislation-standards/current-standards/consolidated_cf_stds__amended_1apr2022.pdf), is "a measure of a lot's genetic worth, with respect to a specific trait". In quantitative terms, a seedlot's genetic worth with respect to a genetic trait B is the weighted average of the genetic value of B of all the trees that contributed with seeds to that lot; the weights in this case is the proportion of cones and pollen each tree has given to the creation of these seeds in relation to the total of cones and pollen used to create the seeds. So the genetic worth of a seedlot with respect to the genetic trait B is given by the formula

GB = B1*(M1 + F1)/2 + ... + Bn*(Mn + Fn)/2

where

Bi is the quantification of tree i's genetic trait B
Mi is the proportion of pollen that tree i has contributed to the generation of this seedlot in relation to the total of pollen given by all trees
Fi is the proportion of cones that tree i has contributed to the generation of this seedlot in relation to the total of cones given by all trees
Pollen contamination

There are cases where we either know or think that the pollen given by one of the trees isn't entirely its own, and the provenance of that pollen is unknown to us. When this happens, we must discard the foreign pollen when calculating the genetic contribution of that tree to the seedlot, so we get to a new formula

GB = BC1*C1 + B1*(M1*(1 - C1) + F1)/2 + ... + BCn*Cn + Bn*(Mn*(1 - Cn) + Fn)/2

where Ci is the estimated percentage of foreign pollen in the tree i's contribution and BCi is the estimated quantification of the contaminant pollen from tree i.

We'll cover these cases for now, so this is the formula we'll be using in this task.

Implementation

We can get the information we need from the following entities:

Pollen contamination, cone and pollen contribution from SeedlotParentTree
Genetic trait quantification from ParentTreeTreeGeneticQualityDto (obtainable from [this endpoint from the Oracle API](https://nr-spar-test-oracle-api.apps.silver.devops.gov.bc.ca/swagger-ui/index.html#/orchard/getParentTreeGeneticQualityData)

We still need to figure out where to get the quantification of the genetic trait for the contaminant pollen.

[PR #156](https://github.com/bcgov/nr-spar/pull/156) contains the work made so far.

Created from task: https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT2-507

### PR DESCRIPTION
**Pull request by RMCampos**
# Description

Creates an Endpoint to do the Generic Worth calculations for all traits.

⚠️ Addded a env var to control the Logging Level. By default (if not defined) will run with INFO level. If you want to see more information, at debug level, you can add `LOGGING_LEVEL=DEBUG` to your `.env` file.

Fixes #240 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

This feature was tested locally, and with unit and integration tests;

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have already been accepted and merged

## Further comments

---
Thanks for the PR!

Any successful deployments (not always required) will be available below.
[Backend](https://nr-spar-379-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-379-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-379-oracle-api.apps.silver.devops.gov.bc.ca/)

Once merged, code will be promoted and handed off to following workflow run.
[Main Merge Workflow](https://github.com/bcgov/nr-spar/actions/workflows/merge-main.yml)

---
Thanks for the PR!

Any successful deployments (not always required) will be available below.
[Backend](https://nr-spar-379-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-379-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-379-oracle-api.apps.silver.devops.gov.bc.ca/)

Once merged, code will be promoted and handed off to following workflow run.
[Main Merge Workflow](https://github.com/bcgov/nr-spar/actions/workflows/merge-main.yml)

### CODE REVIEW

**Comment by RMCampos** [comment]
Ready for review too!!

@paulushcgcj and @craigyu ;)

**Review by paulushcgcj — APPROVED** [review]

**Review by craigyu — COMMENTED** [review]
I'm receiving the following data when trying with the sample post body provided in swagger, is this the expected output? It does not contain any genetic worth value, maybe it's because i'm only providing 1 object data in the body
```json
{
  "geneticTraits": [
    {
      "traitCode": "GVO",
      "traitValue": null,
      "geneticWorthValue": null,
      "percentage": 0
    },
    {
      "traitCode": "WVE",
      "traitValue": null,
      "geneticWorthValue": null,
      "percentage": 0
    },
    {
      "traitCode": "WWD",
      "traitValue": null,
      "geneticWorthValue": null,
      "percentage": 0
    },
    {
      "traitCode": "WDU",
      "traitValue": null,
      "geneticWorthValue": null,
      "percentage": 0
    },
    {
      "traitCode": "AD",
      "traitValue": null,
      "geneticWorthValue": null,
      "percentage": 0
    },
    {
      "traitCode": "DFS",
      "traitValue": null,
      "geneticWorthValue": null,
      "percentage": 0
    },
    {
      "traitCode": "DFU",
      "traitValue": null,
      "geneticWorthValue": null,
      "percentage": 0
    },
    {
      "traitCode": "DFW",
      "traitValue": null,
      "geneticWorthValue": null,
      "percentage": 0
    },
    {
      "traitCode": "DSB",
      "traitValue": null,
      "geneticWorthValue": null,
      "percentage": 0
    },
    {
      "traitCode": "DSC",
      "traitValue": null,
      "geneticWorthValue": null,
      "percentage": 0
    },
    {
      "traitCode": "DSG",
      "traitValue": null,
      "geneticWorthValue": null,
      "percentage": 0
    },
    {
      "traitCode": "IWS",
      "traitValue": null,
      "geneticWorthValue": null,
      "percentage": 0
    }
  ]
}
```

**Comment by craigyu** [comment]
is it necessary to log everything out? 

image

**Comment by RMCampos** [comment]
> when trying with the sample post body provided in swagger, is this the expected output? It does not contain any genetic worth value, maybe it's because i'm only providing 1 object data in the body

Nope. We should log only INFO level. Let me fix out `application.properties` files. Good catch!

**Comment by RMCampos** [comment]
> I'm receiving the following data when trying with the sample post body provided in swagger, is this the expected output? It does not contain any genetic worth value, maybe it's because i'm only providing 1 object data in the body
> 
> ```json
> {
>   "geneticTraits": [
>     {
>       "traitCode": "GVO",
>       "traitValue": null,
>       "geneticWorthValue": null,
>       "percentage": 0
>     },
>     {
>       "traitCode": "WVE",
>       "traitValue": null,
>       "geneticWorthValue": null,
>       "percentage": 0
>     },
>     {
>       "traitCode": "WWD",
>       "traitValue": null,
>       "geneticWorthValue": null,
>       "percentage": 0
>     },
>     {
>       "traitCode": "WDU",
>       "traitValue": null,
>       "geneticWorthValue": null,
>       "percentage": 0
>     },
>     {
>       "traitCode": "AD",
>       "traitValue": null,
>       "geneticWorthValue": null,
>       "percentage": 0
>     },
>     {
>       "traitCode": "DFS",
>       "traitValue": null,
>       "geneticWorthValue": null,
>       "percentage": 0
>     },
>     {
>       "traitCode": "DFU",
>       "traitValue": null,
>       "geneticWorthValue": null,
>       "percentage": 0
>     },
>     {
>       "traitCode": "DFW",
>       "traitValue": null,
>       "geneticWorthValue": null,
>       "percentage": 0
>     },
>     {
>       "traitCode": "DSB",
>       "traitValue": null,
>       "geneticWorthValue": null,
>       "percentage": 0
>     },
>     {
>       "traitCode": "DSC",
>       "traitValue": null,
>       "geneticWorthValue": null,
>       "percentage": 0
>     },
>     {
>       "traitCode": "DSG",
>       "traitValue": null,
>       "geneticWorthValue": null,
>       "percentage": 0
>     },
>     {
>       "traitCode": "IWS",
>       "traitValue": null,
>       "geneticWorthValue": null,
>       "percentage": 0
>     }
>   ]
> }
> ```

Nice catch! I forgot to update the comparision between trait codes. `gvo` is not the same as `GVO`. Now fixed https://github.com/bcgov/nr-spar/pull/379/commits/9bfc990e5984467733981ff22e3f4b4e3df9837c

**Review by craigyu — APPROVED** [review]
Great work!

**Pull request merged**
