### PR TITLE
feat: 834 development of seedlot review step 6   orchard

### LINKED ISSUE #834: Development of Seedlot Review step 6 - Orchard
**Describe the task**
Create FE of Seedlot Review Step 6 (Orchard) and integrate endpoints as you go along. 

Figma design here:  https://www.figma.com/file/ROgZJQezb1DDG4AvEgjtpw/Registration-Process----Reviewer?type=design&node-id=2744-284956&mode=design&t=XxxbormmPMPHmENb-4

Image

**Acceptance Criteria**
- [ ] Developed as per Figma
- [ ] relevant architecture documentation updated
- [ ] tested and merged
- [ ] Develop floater save button place holder - design to be tested by TSC staff

### PR DESCRIPTION
**Pull request by mgaseta**
# Description
Closes #834 

#### New
- Created new Orchard read and edit components
- Added them to the seedlot review view

#### Changed
- Added new `isReview` prop on the orchard step
- Changed `OrchardStep` pollen methodology margin

#### Removed
- Nothing :)

### How was this tested?
- [ ] 🧠 Not needed
- [x] 👀 Eyeball
- [ ] 🤖 Added tests

###  What gif/image best describes this PR or how it makes you feel?

---

Thanks for the PR!

Deployments, as required, will be available below:
- [Frontend](https://nr-spar-35-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1185-backend.apps.silver.devops.gov.bc.ca/actuator/health)
- [Oracle-API](https://nr-spar-1185-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

Please create PRs in draft mode.  Mark as ready to enable:
- [Analysis Workflow](https://github.com/bcgov/nr-spar/actions/workflows/analysis.yml)

After merge, new images are deployed in:
- [Merge Workflow](https://github.com/bcgov/nr-spar/actions/workflows/merge.yml)

### CODE REVIEW

**Review by ngunner15 — CHANGES_REQUESTED** [review]
I found an unusual behaviour on one of the inputs, just wanted to check if its the desired behaviour or not.
orchard_information

**Comment by mgaseta** [comment]
> I found an unusual behaviour on one of the inputs, just wanted to check if its the desired behaviour or not. orchard_information [ orchard_information ](https://private-user-images.githubusercontent.com/31422051/334581660-e4c1dc93-9575-4213-99a0-7463131caf51.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5ODM3NTAsIm5iZiI6MTcxNjk4MzQ1MCwicGF0aCI6Ii8zMTQyMjA1MS8zMzQ1ODE2NjAtZTRjMWRjOTMtOTU3NS00MjEzLTk5YTAtNzQ2MzEzMWNhZjUxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDExNTA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczZGFlYjNjOGMwNGQyYzcxNzJlYzQ1MjNmMTdmYzMzMGMwMzhmZWJjNTIzY2E0ZTY5MGU0NTUxYmE1YzJkOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KU6RvTyjoRgTuK6mJRZPfCXOUjuejkAJEv0-xG4wwww) [ ](https://private-user-images.githubusercontent.com/31422051/334581660-e4c1dc93-9575-4213-99a0-7463131caf51.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5ODM3NTAsIm5iZiI6MTcxNjk4MzQ1MCwicGF0aCI6Ii8zMTQyMjA1MS8zMzQ1ODE2NjAtZTRjMWRjOTMtOTU3NS00MjEzLTk5YTAtNzQ2MzEzMWNhZjUxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDExNTA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczZGFlYjNjOGMwNGQyYzcxNzJlYzQ1MjNmMTdmYzMzMGMwMzhmZWJjNTIzY2E0ZTY5MGU0NTUxYmE1YzJkOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KU6RvTyjoRgTuK6mJRZPfCXOUjuejkAJEv0-xG4wwww)

These are supposed to be read-only, but the design is off, my bad... I'll fix that, thanks for catching it.

**Review by ngunner15 — APPROVED** [review]

**Review by craigyu — APPROVED** [review]

**Review by craigyu — CHANGES_REQUESTED** [review]
Good job, one more thing:
The "add/delete additional orchard" button should be hidden, since users should not be able to edit seedlots

**Comment by mgaseta** [comment]
> Good job, one more thing: The "add/delete additional orchard" button should be hidden, since users should not be able to edit seedlots

Seems to be working fine, can't reproduce this here...

**Review by craigyu — APPROVED** [review]
> feat: adding read-only field for orchard number and name

The reproduction step is that I forgot to pull after you fixed Nisarg's comment 🤦‍♂️

**Pull request merged**
