### PR TITLE
fix: updating repo with latest version of main

### PR DESCRIPTION
**Pull request by RMCampos**
# Description

Updates frontend with latest `ts`, `tsx`, `css` and `scss` files. 

Note: All files were updated by this command: `find . -name '*.scss' -exec cp --parents {} ../nr-spar \;`

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

This STILL NEED to be tested.

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have already been accepted and merged

## Further comments

---
Thanks for the PR!

Any successful deployments (not always required) will be available below.
[Backend](https://nr-spar-51-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-51-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-51-oracle-api.apps.silver.devops.gov.bc.ca/)

Once merged, code will be promoted and handed off to following workflow run.
[Main Merge Workflow](https://github.com/bcgov/nr-spar/actions/workflows/merge-main.yml)

### CODE REVIEW

**Review by mgaseta — DISMISSED** [review]
LGTM! Hope nothing breaks with this merge 🤞🍀🚀

**Comment by craigyu** [comment]
image

I'm having these warning's when running `yarn lint`

**Comment by DerekRoberts** [comment]
> image
> 
> @RMCampos I'm having these warnings when running `yarn lint`
> 
> They are mostly `error Parsing error: Cannot find module '@babel/preset-env'`

I think that's from the line below.  Previously the `src/**` was gone, so the node script ran differently.  I've pulled it back out just to get this PR through.

`    "lint": "./node_modules/.bin/eslint \"src/**\"",`

**Comment by craigyu** [comment]
> image
> 
> @RMCampos I'm having these warnings when running `yarn lint`
> 
> They are mostly `error Parsing error: Cannot find module '@babel/preset-env'`

This issue should be resolved with this [commit](https://github.com/bcgov/nr-spar/pull/51/commits/c7065a4d84a7dfc39a457b82cc6bb342ab398b12)

**Review by DerekRoberts — APPROVED** [review]
Thanks for doing this!  :)

We have a few things to tackle, but in a later sprint/PR.

**Pull request merged**
